/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package zimmerzuteilung;

import java.util.List;
import java.util.ArrayList;
import zimmerzuteilung.algorithmen.Gurobi;
import zimmerzuteilung.objekte.Class;
import zimmerzuteilung.objekte.School;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        List<Gurobi.RULES> constraints = new ArrayList<>();
        constraints.add(Gurobi.RULES.maxStudentsPerRoom);
        constraints.add(Gurobi.RULES.oneRoomPerStudent);
        constraints.add(Gurobi.RULES.onlySameSex);

        School school = new School();
        school.createRandomSchool(5, 2, 1, 3, 1, 5);

        Gurobi.calculate(constraints, school);

    }
}
